### ISSUE TITLE
I'm trying to use MVP for a text classification project, could you please elaborate how?

### ISSUE THREAD

**Issue by johnrhimawan** [RUCAIBox/MVP#10]
> MVP is specially designed for natural language generation and can be adapted to a wide range of generation tasks, including but not limited to summarization, data-to-text generation, open-ended dialogue system, story generation, question answering, question generation, task-oriented dialogue system, commonsense generation, paraphrase generation, text style transfer, and text simplification. Our model can also be adapted to natural language understanding tasks such as sequence classification and (extractive) question answering.

Currently having trouble adapting the model to sequence classification

**Comment by StevenTang1998** [comment]
Could you explain it in detail? You can also refer to the example here https://huggingface.co/docs/transformers/model_doc/mvp#transformers.MvpForSequenceClassification.forward.example.
