### ISSUE TITLE
Broken datasets link

### ISSUE THREAD

**Issue by xgboosting** [RUCAIBox/MVP#4]
Hello, 
Wonderful project, the datasets for fine tuning link in the readme 404's https://drive.google.com/drive/folders/1ZJdXrBhBPtfozPqhIv-Yid9yemXRJiZQ?usp=sharing.

**Comment by SihengLi99** [comment]
I also meet this problem, is there anyone can help ?

**Comment by StevenTang1998** [comment]
Sorry for late response.

The datasets now can be downloaded in https://huggingface.co/RUCAIBox.
