### ISSUE TITLE
fine tuning two tasks at the same time

### ISSUE THREAD

**Issue by zkievanlou** [RUCAIBox/MVP#6]
hello
Thanks for your good repository
Considering that mvp is a multitasking project, how can we fine tune two tasks simultaneously?

**Comment by StevenTang1998** [comment]
I think you can merge two datasets into a new dataset with a new property yaml file.

**Comment by zkievanlou** [comment]
Is it possible that we can fine tune two task such as Paraphrase generation and text classification whit MVP+M( we merge our two datasets into a new dataset)?
In other words, is it possible that we can have two types of outputs(generation and classification) at the same time?

**Comment by StevenTang1998** [comment]
If you format the classification task as a generative task, you easily achieve your goal by merging two datasets into a new one. (this is recommended)
If you want to use a classification head to conduct the classification task, maybe you should modify the code to conduct generation and classification at the same time.

**Comment by zkievanlou** [comment]
thanks a lot.
Is it possible to do two generation tasks at the same time and get two outputs? How?

**Comment by StevenTang1998** [comment]
Just merge them into a new dataset.
